version: "3.3"
services:
    client:
        image: khouloud123456/frontend:localhost
        ports :
            - "3000:3000"
        container_name: frontend
        depends_on: 
            - server 
    server :
        image: khouloud123456/backend:2
        ports: 
            - "5000:5000"
        container_name: backend
