version: "3.3"
services:
    sonarqube:
        image: sonarqube:latest
        ports :
            - "9000:9000"
        volumes:
            - sonar-data:/opt/sonarqube/data
            - sonar-logs:/opt/sonarqube/logs
            - sonar-extension:/opt/sonarqube/extensions
    # nexus :
    #     image: sonatype/nexus3
    #     volumes:
    #         - nexus-data:/nexus-data
    #     ports: 
    #         - "8081:8081"
    #         - "8082:8082"
    #         - "8083:8083"
volumes: 
    sonar-data:
    sonar-logs:
    sonar-extension:
    #nexus-data:
